### ISSUE TITLE
[Bug] - esx property - Issue

### ISSUE THREAD

**Issue by Draco-Fahad** [esx-framework/esx-legacy#725] opened 2022-12-02 03:17 UTC
ACTUALLY I NEED A LITTLE HELP WITH esx property

Sir Iam Using ox inventory for storage
When i save items in esx_property(stash) my item got sorted in sql with no problem.. even after server restart

but after sometime in a running server like after 14 hours my items automatically wiped and i checked the sql the Name has changed >> for example : like from property-11 to property-1111 automatically

FIvem ESX 1.8.5
Windows VPS

**Comment by CsokiHUN** [comment] 2022-12-15 13:19
i think need rewrite server side, and change json save to mysql db
i watched script and fried my brain..

**Comment by Mycroft-Studios** [comment] 2022-12-16 20:52
> i think need rewrite server side, and change json save to mysql db i watched script and fried my brain..

theres no need, this isnt caused by esx property

**Comment by Benzo00** [comment] 2022-12-20 21:34
Not an esx_property issue so i will go ahead and close this

**Closed by Benzo00** 2022-12-20 21:34 UTC
Labels: bug, esx_property
