### ISSUE TITLE
es_extended - throwables, parachutes and gas canisters are not removed by the server

### ISSUE THREAD

**Issue by mcNuggets1** [esx-framework/esx-legacy#370] opened 2022-07-29 12:13 UTC
**Describe the bug**
Parachutes, Gasoline canisters, Throwables etc. aren't removed by the server from the player, when using them all out.
You could just reconnect or relog and have atleast 1 of them again.
Works for parachutes in a way that grants infinite parachutes.

**To Reproduce**
1. Have a parachute
2. Use it
3. See it's gone
4. Rejoin
5. It's back

**Expected behavior**
Misc items getting removed by the server after reaching the end of them.

**Screenshots**
None needed

**Debug Info (please complete the following information):**
Irrelevant

**Additional context**
Not needed

**Comment by michaeld256** [comment] 2022-08-12 13:12
Fixed in #394

**Comment by iSentrie** [comment] 2022-08-24 08:39
that fix was rejected?

**Comment by mcNuggets1** [comment] 2022-09-02 12:54
It wasn't finished.
But no comment from anyone tho.

**Comment by michaeld256** [comment] 2022-09-02 14:19
Yea I was waiting for maintainers feedback on which path to go before commiting the followup solution regarding the possible cheater abuse discussed in the PR.
Got closed for whatever reason though.

**Comment by Gellipapa** [comment] 2022-11-27 04:21
Hi! @mcNuggets1 Thank you for create issue.  I honestly don't know why this issue was closed, but I'm here now and we can talk about it. 

If I understand correctly, the problem is that certain items are not deleted by the server when they are used up?

What is now the status of this fix? 

Thank you for answers.

**Comment by mcNuggets1** [comment] 2022-11-27 07:12
Items are not removed and the fix was closed

**Comment by Gellipapa** [comment] 2022-11-29 19:33
@mcNuggets1  Why must it always run? Can't we check if someone has thrown something away/used it up? What do you think about this?

**Comment by mcNuggets1** [comment] 2022-11-29 19:33
I honestly don't know any game events that do alert us of that event.

**Comment by Gellipapa** [comment] 2022-11-29 20:33
I see. 
```
			CreateThread(function()
				while ESX.PlayerLoaded do
					for i, weapon in ipairs(ESX.GetPlayerData().loadout) do
						local playerHasWeapon = HasPedGotWeapon(ESX.GetPlayerData().ped, GetHashKey(weapon.name), false)

						if not playerHasWeapon then
							TriggerServerEvent('esx:removeWeapon', weapon.name)
						end
					end 


					Wait(1000)
				end
			end)
```

That's what I meant. That's always the run for cycle but really you should only be holding a gun shouldn't you?

**Comment by mcNuggets1** [comment] 2022-11-29 20:43
I didn't create the code.
Optimising the code would look the following:
- check only for a few weapons, that actually can be removed from inventory
- allow serverside removal only of these weapons
- optimise the poorly written code and maybe don't update every second (also maybe do it serverside, not clientside)

**Comment by Gellipapa** [comment] 2022-11-29 21:06
@mcNuggets1 Oh sorry you just commented there. #394 Could you then write it as you say and if it's good we'll accept it?

**Comment by mcNuggets1** [comment] 2022-11-29 21:17
Whenever I get the time, I could take a look at it.
Currently Im a little bit busy however.

**Comment by Gellipapa** [comment] 2022-11-29 21:19
No problem, thank you on behalf of the ESX team.

**Closed** 2022-12-15 12:48 UTC
Labels: bug, wontfix
