### ISSUE TITLE
[Bug] - esx_textui - esx_property - issue

### ISSUE THREAD

**Issue by dandi83** [esx-framework/esx-legacy#693] opened 2022-11-22 16:12 UTC
When I go to the property management blip it gives me this error

https://imgur.com/Bjaq2c5

**Comment by amgmacht** [comment] 2022-11-24 11:08
same 

https://prnt.sc/2RucYD5kytwq

**Comment by WhIverson23** [comment] 2022-11-24 20:55
I confirm the same thing, the question is when it's gonna be fixed :/
https://prnt.sc/BPGDui9WM7TF

**Comment by CsokiHUN** [comment] 2022-11-24 22:32
Fixed in #700.
Please close the issue @Benzo00

**Comment by Unavarage** [comment] 2022-11-24 23:37
Yup, I tested it, works everything normal.

**Comment by bitpredator** [comment] 2022-11-25 20:02
seems not to work for esx_banking.
![esx_banking error](https://user-images.githubusercontent.com/67551273/204050517-ed69b3b1-268b-4f07-ac32-7e03a64b9073.PNG)

**Comment by CsokiHUN** [comment] 2022-11-25 20:04
> seems not to work for esx_banking. ![esx_banking error](https://user-images.githubusercontent.com/67551273/204050517-ed69b3b1-268b-4f07-ac32-7e03a64b9073.PNG)

this is another bug. @Rav3n95 check please.

**Comment by Rav3n95** [comment] 2022-11-25 20:28
> > seems not to work for esx_banking. ![esx_banking error](https://user-images.githubusercontent.com/67551273/204050517-ed69b3b1-268b-4f07-ac32-7e03a64b9073.PNG)
> 
> this is another bug. @Rav3n95 check please.

When is this happening? On my end ui work just fine

**Comment by Rav3n95** [comment] 2022-11-25 20:29
@Gellipapa

**Comment by bitpredator** [comment] 2022-11-25 20:41
> > > sembra non funzionare per esx_banking.![errore esx_banking](https://user-images.githubusercontent.com/67551273/204050517-ed69b3b1-268b-4f07-ac32-7e03a64b9073.PNG)
> > 
> > 
> > questo è un altro bug.@Rav3n95Controlli, per favore.
> 
> Quando sta accadendo? Da parte mia, funziona bene



> 
According to my tests, this happens when ATMs are used at small shops, specifically when depositing or withdrawing money.

**Comment by Rav3n95** [comment] 2022-11-25 22:05
> 

Tested, i have 0 error on EN lang

**Comment by bitpredator** [comment] 2022-11-25 23:02
I'm testing it with the Italian language, maybe the problem is there.

**Comment by Gellipapa** [comment] 2022-11-26 01:45
Hi! Yes, there were one or two typos in the translation and one or two minor mistakes that made it not work as it should. 
Fixed #708 :) 

Thanks for your patience!

**Comment by bitpredator** [comment] 2022-11-26 16:08
> Hi! Yes, there were one or two typos in the translation and one or two minor mistakes that made it not work as it should and add new feature you will now be able to create bank logs in other scripts. For more information, see the readme. Fixed #708 :)
> 
> Thanks for your patience!

I tried the fixes, they work fine

**Comment by Gellipapa** [comment] 2022-11-26 20:14
Done.

**Closed by Gellipapa** 2022-11-26 20:14 UTC
Labels: bug
