### ISSUE TITLE
the last extended version i find a bug

### ISSUE THREAD

**Issue by xXJay809Xx** [esx-framework/esx-legacy#730] opened 2022-12-04 23:48 UTC
Hi i found a bug on the last extended version that every time i put a car in the garage…the car is coming out whith all the extra on it …. And I take all the extra off the car and put it in the garage and is adding it again ....

**Comment by xXJay809Xx** [comment] 2022-12-06 01:18
And other big bug staring from version 1.8.5 to the last update still happening is … when a player lock and unlock they car or when a player slap other player everyone can hear it being far from other player let say like cross the map….

**Comment by iSentrie** [comment] 2022-12-06 14:15
esx has lock/unlock script?

**Comment by xXJay809Xx** [comment] 2022-12-06 14:20
To lock the car door ….when a player get out of the car and lock the door

**Comment by iSentrie** [comment] 2022-12-06 16:57
i know so I'm asking does esx has this?

**Comment by xXJay809Xx** [comment] 2022-12-06 23:36
yeah... the bug when a player lock and unlock they car  other player can hear it being far from that player

**Comment by iSentrie** [comment] 2022-12-07 12:32
you being weird bro. idk how that's related to esx official scripts, can you please point that out or you just don't know what your are talking about?

**Comment by xXJay809Xx** [comment] 2022-12-07 12:55
I use cd_garage scrip
And the car door lock is carremote scrips 

I’m trying to tell you that problem that I have right now that never happened before on Legacy old version … if you want I could come when you get a chance to my server and I could show you what’s is going on…. Like that you can understand better

**Comment by iSentrie** [comment] 2022-12-07 13:28
regarding **garage**, ask script creator not here.
regarding car door lock, u switched to onesync, which changes some things, update your interact sound or xsound and look for info elsewhere, this is not related to esx-framework.

close this issue please

**Comment by xXJay809Xx** [comment] 2022-12-07 13:38
This bug don’t has nothing to do with the garage or car lock because I Tested on QBcore framework and this didn’t happen but ok I just want to let you know about the problem …..but ok

**Comment by iSentrie** [comment] 2022-12-08 17:55
qb and esx use completely different scripts, same as you.

extras are handled perfectly fine, what's wrong is liveries, it's broken for months.
global sounds are caused by bad choice of your scripts which is not related to ESX at all.

close the issue.

**Closed** 2022-12-08 17:58 UTC
Labels: bug
