### ISSUE TITLE
ERROR [Bug] - esx_skin - error on start resource

### ISSUE THREAD

**Issue by timonation** [esx-framework/esx-legacy#705] opened 2022-11-25 18:12 UTC
restart esx_skin results in an error

**Comment by timonation** [comment] 2022-11-25 18:13
https://discord.com/channels/513374574394474531/1008401371122372789/1045526236119711795

**Comment by CsokiHUN** [comment] 2022-11-26 20:18
I couldn't reproduce it.
Old es_extended version, update it and the TranslateCap function will be available

**Comment by Gellipapa** [comment] 2022-11-27 01:14
@timonation Hi! Please update latest version and retest. Thank you.

**Comment by Zzeyy** [comment] 2022-11-27 17:19
I'm running 1.8.5 es_extended but I still get errors with global 'TranslateCap'

**Comment by Gellipapa** [comment] 2022-11-27 23:33
Try update latest version.

**Comment by TheFantomas** [comment] 2023-01-08 16:41
I think we can close this post already. The fault is not on the esx side... And the advice was given to him.

**Comment by Zzeyy** [comment] 2023-01-09 14:26
I don't really know what else script would be causing that as no other
script even works with the mechanicjob, but sure, close it.

**Comment by Gellipapa** [comment] 2023-01-09 21:20
@Zzeyy Hi! Yes we can't reproduce your problem, i think you need download latest esx_legacy version. I take a picture restart esx_skin but i don't see error. Thank you for report.
![image](https://user-images.githubusercontent.com/22717950/211410210-c9a3388c-7a6e-4fad-87cf-fc4b7745347f.png)

**Closed by Gellipapa** 2023-01-09 21:20 UTC
Labels: bug, awaiting feedback
